// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bitespeed/config"
	"bitespeed/delivery"
	"bitespeed/repository"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func InitializeDependency(cfg *config.StartupConfig) (*App, error) {
	database, err := newDatabase(cfg)
	if err != nil {
		return nil, err
	}
	contactRepo := repository.NewContactRepo(database)
	contactHandler := delivery.NewContactHandler(contactRepo)
	echo := newRouter(contactHandler)
	app := newApp(cfg, echo)
	return app, nil
}
